name: Publish to GitHub Packages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.4.2

      - name: Publish
        run: ./gradlew publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
